const SVGS = {
  setting: 'setting',
  search: 'search',
  json: 'json',
  base64: 'base64',
  string: 'string',
  html: 'html',
  develop: 'develop',
  theme: 'theme',
  language: 'language',
  moreMenu: 'more-menu',
  rabbit: 'rabbit',
  google: 'google',
  baidu: 'baidu',
  bing: 'bing',
  yahoo: 'yahoo',
  readFile: 'readFile',
  upload: 'upload',
  application: 'application',
  shop: 'shop',
  social: 'social',
  game: 'game',
  media: 'media',
  youtube: 'youtube',
  bilibili: 'bilibili',
  tiktok: 'tiktok',
  netflix: 'netflix',
  hulu: 'hulu',
  dailymotion: 'dailymotion',
  appleMusic: 'apple_music',
  iqiyi: 'iqiyi',
  youku: 'youku',
  tencentVideo: 'tencentVideo',
  mangotv: 'mangotv',
  pptv: 'pptv',
  netEaseCloud: 'netEaseCloud',
  tencentMusic: 'tencent_music',
  github: 'github',
  applicationSetting: 'application_setting',
  yaml: 'yaml',
  xml: 'xml',
  url: 'url',
};

export default SVGS;
