import React from 'react';
import Head from 'next/head';
import { useTranslation } from '../hooks';
import Button from '@mui/material/Button';

export default function Home() {
  const t = useTranslation();
  return (
    <>
      <Head>
        <title>{t('title')}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div>
        <Button variant="contained">Hello World</Button>
      </div>
    </>
  );
}
